dst=../../../build/2Dviews/

all:
	@echo "----------------------------"
	@echo "Deploy :2Dviews"	
	@echo "___"
	webpack
	@echo "----------------------------"
clean:
	@echo "----------------------------"
	@echo "Clean :2Dviews"	
	@echo "___"
	rm -f $(dst)/*
	@echo "-------------------------"
