all: clean
	@echo "----------------------------"
	@echo "build Images"
	@echo "----------------------------"
	mkdir ../../../build/client/img/
	cp ./*.png ./*.gif ./*.jpg ../../../build/client/img/
	cp -r ./layout ../../../build/client/img/
clean:
	@echo "----------------------------"
	@echo "clean CSS"
	@echo "----------------------------"
	rm -rf ../../../build/client/img
