all: clean
	@echo "----------------------------"
	@echo "build Javascripts"
	@echo "----------------------------"
	webpack
clean:
	@echo "----------------------------"
	@echo "clean Javascripts"
	@echo "----------------------------"
	rm -rf ../../../build/client/js/
