dst=../../../build/public/

all:
	@echo "----------------------------"
	@echo "Deploy :controllers"	
	@echo "___"
	webpack
	@echo "----------------------------"
clean:
	@echo "----------------------------"
	@echo "Clean :controller"	
	@echo "___"
	rm -f $(dst)
	@echo "-------------------------"
