all: clean
	@echo "----------------------------"
	@echo "build CSS"
	@echo "----------------------------"
	mkdir ../../../build/client/css/
	cp ./*.css ../../../build/client/css/
clean:
	@echo "----------------------------"
	@echo "clean CSS"
	@echo "----------------------------"
	rm -rf ../../../build/client/css
