all: clean
	@echo "----------------------------"
	@echo "build HTML"
	@echo "----------------------------"
	cp ./template.html ../../../build/client/index.html
clean:
	@echo "----------------------------"
	@echo "clean HTML"
	@echo "----------------------------"
	rm -f ../../../build/client/*.html
